apiVersion: v1
kind: Pod
metadata:
  name: http-go-v2
  labels:
    creation_method: manual-v2
spec:
  containers:
  - name: http-go
    image: amanaksu/http-go
    ports:
    - containerPort: 8080
      protocol: TCP