apiVersion: v1
kind: Service
metadata:
  name: http-go-np
spec:
  selector:
    run: http-go
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30001

---

apiVersion: v1
kind: Service
metadata:
  name: http-go-svc
spec:
  selector:
    run: http-go
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-go
  labels:
    run: http-go
spec:
  replicas: 1
  selector:
    matchLabels:
      run: http-go
  template:
    metadata:
      labels:
        run: http-go
    spec:
      containers:
      - name: http-go
        image: amanaksu/http-go
        ports:
        - containerPort: 8080